/**
*	@api {post} /collection Create New Collection
*	@apiVersion 1.5.1
*	@apiDescription Creates a new collection.
*	@apiName AddCollection
*	@apiGroup Collections
*
*	@apiPermission Any Authenticated User
*
*	@apiHeader {String} Authorization Authorization Token
*
*	@apiParam (Body Parameters) {Number{4}} code ID Code of Site
*	@apiParam (Body Parameters) {Number} customer Customer Number
*	@apiParam (Body Parameters) {Object[]} products Array of Products to be Collected
*	@apiParam (Body Parameters) {String} products.ean EAN of Product to be Collected
*	@apiParam (Body Parameters) {String} products.quantity Quantity of Product to be Collected
*
*	@apiParamExample {json} Request Example:
*		POST /collection
*		{
*			"code": 1111,
*			"customer": 1000000000,
*			"products": [
*				{
*					"ean": "1234567890123",
*					"quantity": 2
*				},
*				{
*					"ean": "1234567890124",
*					"quantity": 5
*				},
*				...
*			]
*		}
*
*	@apiSuccessExample {json} Success Example:
*		HTTP/1.1 201 Created
*		{
*		    "code": 201,
*		    "status": "Created",
*		    "description": "Collection Added Successfully",
*		    "data": 2000000000 // Collection Number Generated by Server
*		}
*
*	@apiErrorExample {json} Error Example 1:
*		// Returned when collection number is already in use (try again to get a new one)
*		HTTP/1.1 409 Conflict
*		{
*		    "code": 409,
*		    "status": "Conflict",
*		    "description": "Collection Number Already in Use",
*		    "data": []
*		}
*	@apiErrorExample {json} Error Example 2:
*		// Returned when required fields are missing from request body
*		HTTP/1.1 400 Bad Request
*		{
*		    "code": 400,
*		    "status": "Bad Request",
*		    "description": "Invalid Request Body",
*		    "data": []
*		}
*/