/**
*	@api {post} /customer Create New Customer
*	@apiVersion 1.5.1
*	@apiDescription Creates a new customer.
*	@apiName AddCustomer
*	@apiGroup Customers
*
*	@apiPermission Any Authenticated User
*
*	@apiHeader {String} Authorization Authorization Token
*
*	@apiParam (Body Parameters) {String="Mr","Ms","Mrs","Miss","Mx"} title Title of Customer
*	@apiParam (Body Parameters) {String} firstName First Name of Customer
*	@apiParam (Body Parameters) {String} lastName Last Name of Customer
*	@apiParam (Body Parameters) {String} email Email Address of Customer
*	@apiParam (Body Parameters) {String} password Customer's Password for Online Account
*	@apiParam (Body Parameters) {String} addressNumberName House Number of Name of Customer's Address
*	@apiParam (Body Parameters) {String} addressStreet1 Address Line 1 of Customer's Address
*	@apiParam (Body Parameters) {String} [addressStreet2] Address Line 2 of Customer's Address
*	@apiParam (Body Parameters) {String} addressCity City of Customer's Address
*	@apiParam (Body Parameters) {String} addressPostcode Postcode of Customer's Address
*	@apiParam (Body Parameters) {String} mobilePhone UK Mobile Phone Number of Customer
*
*	@apiParamExample {json} Request Example:
*		POST /customer
*		{
*			title: 'Mr',
*			firstName: 'John',
*			lastName: 'Smith',
*			email: 'example@example.com',
*			password: 'password',
*			addressNumberName: '1',
*			addressStreet1: 'Test Street',
*			addressCity: 'Test Town',
*			addressPostcode: 'AB12CD',
*			mobilePhone: '07123456789'
*		}
*
*	@apiSuccessExample {json} Success Example:
*		HTTP/1.1 201 Created
*		{
*		    "code": 201,
*		    "status": "Created",
*		    "description": "Customer Added Successfully",
*		    "data": 1000000000 // Customer Number Generated by Server
*		}
*
*	@apiErrorExample {json} Error Example 1:
*		// Returned when customer number is already in use (try again to get a new one)
*		HTTP/1.1 409 Conflict
*		{
*		    "code": 409,
*		    "status": "Conflict",
*		    "description": "Customer Number Already in Use",
*		    "data": []
*		}
*	@apiErrorExample {json} Error Example 2:
*		// Returned when required fields are missing from request body
*		HTTP/1.1 400 Bad Request
*		{
*		    "code": 400,
*		    "status": "Bad Request",
*		    "description": "Invalid Request Body",
*		    "data": []
*		}
*/