/**
*	@api {post} /delivery Create New Delivery
*	@apiVersion 1.5.1
*	@apiDescription Creates a new delivery.
*	@apiName AddDelivery
*	@apiGroup Deliveries
*
*	@apiPermission Any Authenticated User
*
*	@apiHeader {String} Authorization Authorization Token
*
*	@apiParam (Body Parameters) {Number{4}} outbound ID Code of Sending Site
*	@apiParam (Body Parameters) {Number{4}} inbound ID Code of Receiving Site
*	@apiParam (Body Parameters) {Date} arrivesAt Date Delivery is Due to Arrive (Format: YYYY-MM-DD)
*	@apiParam (Body Parameters) {Object[]} products Array of Products to be Delivered
*	@apiParam (Body Parameters) {String} products.ean EAN of Product to be Delivered
*	@apiParam (Body Parameters) {String} products.quantity Quantity of Product to be Delivered
*
*	@apiParamExample {json} Request Example:
*		POST /delivery
*		{
*			"outboumd": 1111,
*			"inbound": 1112,
*			"arrivesAt": "2021-12-31",
*			"products": [
*				{
*					"ean": "1234567890123",
*					"quantity": 2
*				},
*				{
*					"ean": "1234567890124",
*					"quantity": 3
*				},
*				...
*			]
*		}
*
*	@apiSuccessExample {json} Success Example:
*		HTTP/1.1 201 Created
*		{
*		    "code": 201,
*		    "status": "Created",
*		    "description": "Delivery Added Successfully",
*		    "data": 3000000000 // Delivery Number Generated by Server
*		}
*
*	@apiErrorExample {json} Error Example 1:
*		// Returned when delivery number is already in use (try again to get a new one)
*		HTTP/1.1 409 Conflict
*		{
*		    "code": 409,
*		    "status": "Conflict",
*		    "description": "Delivery Number Already in Use",
*		    "data": []
*		}
*	@apiErrorExample {json} Error Example 2:
*		// Returned when required fields are missing from request body
*		HTTP/1.1 400 Bad Request
*		{
*		    "code": 400,
*		    "status": "Bad Request",
*		    "description": "Invalid Request Body",
*		    "data": []
*		}
*/